language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t onikitin03/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true onikitin03/docker-react npm run test


